project: main.o Polynomial.o
	g++ -g main.o Polynomial.o -o project

main: main.cpp Polynomial.h
	g++ -g -c main.cpp -o main.o

Polynomial: Polynomial.cpp Polynomial.h
	g++ -g -c Polynomial.cpp -o Polynomial.o
